substitutions:
  _LOCATION: asia-northeast1
  _REPOSITORY: version-kihon
  _IMAGE_NAME: version-kihon
  _TAG: $SHORT_SHA         # ← $COMMIT_SHA で空になるケース対策
  _SERVICE_NAME: version-kihon
  _REGION: asia-northeast1

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # ====== Step 1: Build & Push ======
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_TAG}
      - --dockerfile=./Dockerfile
      - --context=.
      - --cache=true
      - --cache-ttl=8h
      - --compressed-caching=false
      - --cache-copy-layers=true
    id: "Build & Push"

  # ====== Step 2: Deploy to Cloud Run ======
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_TAG}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --memory
      - "2Gi"           # ← クォートで囲む
      - --concurrency
      - "10"            # ← クォート（"1" でもOKだが10推奨）
    id: "Deploy"
